### ISSUE TITLE
JS Error on IE6/7

### ISSUE THREAD

**Issue by ZaDarkSide** [harrydeluxe/extjs-ux#1]
On IE6 or IE7 i get this error, on other browsers is fine.
SCRIPT5007: Unable to get value of the property 'getScroll': object is null or undefined 
`if (Ext.isIE) {
                setTimeout(function() {
                    this.scroller.scrollTo('top', this.scroller.getScroll().top - 40); //bug
                }, 100);
            } else {`
DragSelector.js

**Comment by harrydeluxe** [comment]
Thanks for the note. Is fixed.
