### ISSUE TITLE
RowEditing and DragSelector combined bug

### ISSUE THREAD

**Issue by ZaDarkSide** [harrydeluxe/extjs-ux#2]
When you have RowEditing and also DragSelector as a plugin for the grid when you click to edit the row I think DragSelector "eats" the onClick event for the RowEditing and prevents you from selecting/focusing a cell/form/input to edit.

**Comment by ZaDarkSide** [comment]
Possible fix:

DragSelector.js

`onBeforeStart: function(e) {
        if (e.button === 0 && e.target.className.indexOf('x-form-field') != -1) {
            return false;
        }`

This condition isn't working for me:

`// return false if any grid editor is active
        if (this.grid.activeEditor && this.grid.activeEditor !== null) {
            return false;
        }`

**Comment by harrydeluxe** [comment]
fixed
