### ISSUE TITLE
Sencha Cmd build failure with exception 'com.sencha.exceptions.ExParse' for Ext.ux.form.field.TinyMCEWindowManager

### ISSUE THREAD

**Issue by narramadan** [harrydeluxe/extjs-ux#24]
Hi,

Thanks for the wonderful plugin. Its works as expected when used in the application and accessed without minify.

But when used with Sencha Cmd, getting parse exception for TinyMCEWindowManager. Identified that it is extending tinymce.WindowManager. 

Tried step as mentioned here http://www.sencha.com/forum/showthread.php?170566-Tinymce-with-Ext-4.0.7&p=980917&viewfull=1#post980917. It didnt resolve the build error.

Are there any other changes to be done ? It would be helpful to all seeking this issue who uses sencha cmd.

Thanks,
Madan N

**Comment by JoeJErnst** [comment]
I was able to get past this error by removing the extend: tinymce.WindowManager line in TinyMCEWindowManager.js

**Comment by narramadan** [comment]
Thanks...This fixed the issue and the app worked as expected after sencha cmd...
