### ISSUE TITLE
Ext.ux.grid.feature.Tileview bug with drag selector

### ISSUE THREAD

**Issue by ZaDarkSide** [harrydeluxe/extjs-ux#25]
In the example http://harrydeluxe.github.io/extjs-ux/example/grid/tileview.html

Dragging and selecting something and then switching over to icon view, tile view, detail view etc, makes the drag selector rectangle invisible, the selection works but the rectangle becomes invisible.

**Comment by byhell** [comment]
quick fix just add this line to the onStart function

onStart: function(e)
{
        var me = this;
 -->       me.proxy = null;
        me.getProxy().show();
        me.scrollTopStart = me.scroller.getScroll().top;
        me.fillAllRegions();
        me.dragging = true;
        me.fireEvent('dragselectorstart', me);
 }
