### ISSUE TITLE
tinyMCE field removal can cause an error if its not initialized

### ISSUE THREAD

**Issue by martinsbalodis** [harrydeluxe/extjs-ux#3]
I am getting an error if I am removing form panel with tinymce field which is not yet shown to user. Here is an [example](http://jsfiddle.net/4d2J6/1/) with the field in a tab. If you close tab then you get an error `Uncaught TypeError: Cannot call method 'destroy' of undefined`. But you won't get the error if you open the tab and then close it afterwards. 
You could solve this by checking whether the tinymce object is initialized:
`ux/form/field/TinyMCE.js`

``` javascript
    onDestroy: function()
    {
        var me = this;

        //me.editor.remove();
        if(me.editor){
            me.editor.destroy();
        }
        me.callParent(arguments);
    },
```

**Comment by harrydeluxe** [comment]
Thank you. Fixed.

**Comment by martinsbalodis** [comment]
Similar error happens when saving form and the tinymce field is in a panel. If I don't open the tab then value retrieval from field fails. This worked for me:

``` javascript
getValue: function()
    {
        if(this.editor) {
            return this.editor.getContent();
        }
        else {
            return this.value;
        }

    },
```

**Comment by harrydeluxe** [comment]
Thank you. Fixed.
