### ISSUE TITLE
Size and custom setup of tinyMCE editor

### ISSUE THREAD

**Issue by elchiapp** [harrydeluxe/extjs-ux#9]
Hi! I just wanted to let you know that me and my colleagues have encountered (and fixed for ourselves, hope it's useful to you too) a few "bugs":

1) TinyMCE.js

It wouldn't load any custom setup configuration given in the tinyMCE configuration object. This does the trick:

```
me.tinymceConfig.setup = function(editor){
    // Load custom setup
    me.tinymceConfig.mysetup(editor); //called as an external function giving the editor as argument
    ...
}
```

2) TinyMCE.js

Completely redifined the onResize function and added the onResize event in function initEditor. Here's the body of the new function:

```
onResize: function(component, adjWidth, adjHeight)
{

    if(component.iframeEl)
    {
        // CIRSFID octavian-marco : width and height changed 
        component.iframeEl.setWidth(this.getWidth());
        component.iframeEl.setHeight(this.getHeight()-45);
    }

    if(component.tableEl)
    {
        // CIRSFID octavian-marco : width changed  and height changed
        component.tableEl.setWidth(this.getWidth());
        component.tableEl.setHeight(this.getHeight()-45);
    }
},
```

3) TinyMCE.js

Fired resize event to adapt the editor's size to the parent panel.

```
editor.onPostRender.add(function(editor)
        {
           ....
          me.fireEvent('resize', me);
          ...
         }
}
```

Have a nice day!
## 

Marco Chiappetta

**Comment by harrydeluxe** [comment]
Many thanks! With the recent changes I've solved it differently.

**Comment by elchiapp** [comment]
Thank you very much for the latest upgrade! Things work much better about resizing! The only remaining issue is the loading of a custom setup for the editor frame. Am I missing a new way of doing it or it can't be done yet? (I'm still using the mysetup workaround). Thanks in advance and have a nice day!
